### ISSUE TITLE
Is aws-sdk installed by default?

### ISSUE THREAD

**Issue by yspreen** [fusebit/everynode#3]
I'm getting issues using serverless-bundle. It always excludes the aws-sdk package from bundles.

**Comment by tjanczuk** [comment]
@yspreen The aws-sdk is not installed by default (see https://github.com/fusebit/everynode#faq), you need to include it in your deployment package to use it. We've decided not to couple the version of aws-sdk with the version of Node.js and leave the choice of aws-sdk version to the developers instead.
