### ISSUE TITLE
Fusebit Logo Link

### ISSUE THREAD

**Issue by geoffreywiseman** [fusebit/everynode#4]
There's a space in the Fusebit URL at the top of the README.md that the fuse bit logo links to. 

I tried a couple of different browsers, and neither of them would navigate to Fusebit, which means that people can't easily click through.

I could make a PR, but a forking your codebase and making a PR to remove a single space is probably overkill. ;)

**Comment by tjanczuk** [comment]
@geoffreywiseman Thank you for reporting this, it is fixed now!
